### ISSUE TITLE
Quest Loot Bug with Party

### ISSUE THREAD

**Issue by ceresia** [tkrokli/TrinityCore#4]
TrinityCore Rev. 3761d24 2015-04-21 13:26:30 +0200 (3.3.5 branch) (Win64, Release)

Player 1 and Player 2 party up.
They both take the quest labeled "Elixir of Suffering" in Hillsbrad Foothills.
They are both within a couple feet of the monster, monster is killed.
Both players can loot corpse, but after Player 1 loots, it still shines for Player 2 but there is no quest loot available anymore to Player 2. In retail each player was able to receive quest loot.

This happens on A LOT of quests, perhaps all of them. It was happening in the last release and still happening on this one.

![Empty Monster](https://scontent-ord.xx.fbcdn.net/hphotos-xat1/t31.0-8/11146388_10206283067293805_7512129054653651091_o.jpg)

![Quest Log](https://fbcdn-sphotos-f-a.akamaihd.net/hphotos-ak-xpf1/v/t1.0-9/10981855_10206283067253804_4372195950286909201_n.jpg?oh=46cf8626fdabf926b391144f3bbb0cd2&oe=55D7AD37&__gda__=1439985480_4d0dbac4243126412c143e2ad82994c7)

**Comment by ceresia** [comment]
Has anyone been able to test this besides me?

This bug makes it a mess to have a big party of friends do these types of quests.

I'm surprised no one else has said anything.

**Comment by tkrokli** [comment]
Sorry, been too occupied. I haven't even had time to ask in the TC forum. I am going to put it on my work list for tonight, though, together with that issue of non-working quests in the Draenei starting area.

**Comment by ceresia** [comment]
Yes, let me know if you need video, or if you need me to test another revision, I will be happy to, I know the players on my server are very anxious to get this quest loot bug fixed, they are trying to stay away from utilizing parties to complete quests, and I have lost a couple players already.

Wish I knew how to fix all of these things :/

**Comment by tkrokli** [comment]
OK, I'm going to start testing it now. I wasted all weekend trying to fix documentation for the Feyzee LFG fix for my ike3 AI Playerbot repack. I have not had time to do anything else at all, not even go out of my house. The source files are mainly undocumented (unless you browse through 2100 files and find which ones have got the changes from Feyzee) and the folder itself exists only in a limited set of copies that also contain old TrinityCore source files without the changes. It is hard to deal with undocumented material.

**Comment by tkrokli** [comment]
**TrinityCore rev. d74640aa7fdd 2015-05-04 15:11:05 +0100 (3.3.5 branch) (Win64, Release)**

![quest_log_shared_participants](https://cloud.githubusercontent.com/assets/4903600/7461622/a1c980da-f2ab-11e4-997f-d30d74e00579.png)  ![quest_log_shared](https://cloud.githubusercontent.com/assets/4903600/7461680/f7cc7f28-f2ab-11e4-9836-fed205d94245.png) 

![quest_log_shared_items_and_roll_in_chat](https://cloud.githubusercontent.com/assets/4903600/7461557/6983dc7a-f2ab-11e4-9a76-30e9492e53b7.png)

![quest_log_shared_full_image](https://cloud.githubusercontent.com/assets/4903600/7461469/d344096a-f2aa-11e4-8585-71566d5bcad4.png)

Just as you can see from what happened here, after a long consideration about how I should test this and also a lot of preparations for each character, I finished testing the problem only after 15 minutes.

1. Quest items can sometimes be looted from the same kill, but not always.
2. Read all the old online comments about the quest on this page: http://www.wowhead.com/quest=496/deprecated-elixir-of-suffering
3. This is a visual bug, making it look like it is possible to loot the killed creature, but it should not be like this. Some kinds of loot is not shared, even if it is quest loot.
4. Try increasing the `corpse.decay` time in Worldserver.conf if the dead creature despawns too quickly to test for what is actually happening.
5. Since looting shared quest items seem to work for me, I can't really claim that I have got enough evidence or documentation to open an issue about it in the TrinityCore issue tracker.

**Comment by ceresia** [comment]
It's reasonably simple for us to test, I had three different accounts within the party.  All quests we quested with at that time, zone being Hillsbrad and Alterac.  If there are three of us, we would have to kill 30 monsters to get 10 items each, never would a monster let multiple players loot it.  It appeared as looted, but never was anyone able to after the first person looted.

Now a kicker:

If loot for that monster was for person A alone, person B or C could steal the quest item first, and person A would be able to loot everything else, but not have a quest item available to them.  The corpse would appear lootable by all parties.

I attempted to increase the time where the corpse would decay, but this didn't do anything at all.

Remembering back to retail, if Person B would loot corpse and receive quest item, then Person A and C could get quest item as well.  If person B looted corpse and no quest item available, then Person A and person C would also NOT get a quest item.

My friends that played Vanilla, BC, and Wotlk all state that the behavior we are experiencing is not retail like.

I'm not sure what to do from here, I can make videos or additional screenshots.   :/

**Comment by ceresia** [comment]
I guess I can also wait until 1.5 is available and test additionally there as well, this is your call.

**Comment by ceresia** [comment]
Also a bug concerning these quests:

Regardless of who gets the quest item, and the player the random loot belongs to is looted, you cannot skin the monster, it refuses to allow you to skin, still shows there is loot, but that is where my empty loot box comes in.

**Comment by tkrokli** [comment]
Your guess is as good as mine, you can choose to report it to TrinityCore if you like. I need to focus on what I have promised others to do, like updating my other repacks. I need at least 3 weeks break from Jeutie's repack now, to finish any other work at all. Now I know why Jeuite went out drinking more when he was working on a repack than now after he quit. It is a lonely job and often very troubled. Once a repack is released, I don't have the responsibility for the contents, except for keeping my word that the files are what I have described on the download page.
