### ISSUE TITLE
Quest - Where in the World is Hemet Nesingwary? - Quest ID 12521

### ISSUE THREAD

**Issue by ceresia** [tkrokli/TrinityCore#8]
Not necessary an issue with the quest, but the way you get there:

NPC ID: 24160 - Archmage Pentarus
NPC/Creature ID: 28192 - Archmage Pentarus' Flying Machine

Upon taking quest 12521 you are able to speak with NPC 24160 again and request "I'm ready to fly to Sholazar Basin"

I see some issues around this, but my experiments are different:

First attempt:  I was put on the flying mount, not ported to Sholazar, but instead started flying towards Icecrown and then ultimately though a mountain underneath the world and it went on forever, had to GM port the char back to Dalaran

Second attempt:  Oddly enough I was ported to Sholazar, very crappy movement with the Flying Machine, but once ported to Sholozar, I was stuck in mid air, bouncing up and down indefinitely.  

Unsure if you want to add this to the main TrinityCore or not.

TY

**Comment by tkrokli** [comment]
" **Archmage Pentarus gossip menu #10796** "

dr-j : " [...] when you select the gossip option, you get "You can't do that now" in red writing, in the middle of the screen, even though you do mount and wp start. And once you teleport to sholazar basin, the flying machine just stays above rivers heart and nothing else happens, is this meant to be the case? " (https://github.com/TrinityCore/TrinityCore/issues/10796#issuecomment-66920627)

Pitcrawler: "I don't think so, the video shows the expected behavior." (https://github.com/TrinityCore/TrinityCore/issues/10796#issuecomment-66922038)

Killyana : "On the first time when you run the quest after a crash or a reboot, the issue "Once you teleport to sholazar basin the flying machine just stays above rivers" can happen. It seems the flying machine start the WP from Dalaran instead the position on sholazar basin, you can see this if you dismount some seconds or minutes after the teleportation if the issue happen. I cannot find the origin of this behavior." (https://github.com/TrinityCore/TrinityCore/issues/10796#issuecomment-66922695)
